### ISSUE TITLE
Cannot access some data structures when importing with ES6 style imports

### ISSUE THREAD

**Issue by monkey-jeff** [raml-org/webapi-parser#67]
We are working on writing tests for some of the apis in webapi parser.  

We are using typescript and there is a d.ts file provided in the npm package, but it seems as if it is incomplete.

When we use require typescript doesn't resolve the type definitions and that seems to work, for example the following code will work

```typescript
const webapi = require('webapi-parser')

it("webapi test", async () => {
 webapi.WebApiParser.init();

  const api = new webapi.model.domain.WebApi();
  const model = new webapi.model.document.Document(api)
  ...
  expect(getBaseUri(model)).to.equal(
    "test-url-value"
  );
});

```

where as when talking about this code

```typescript
import webapi from "webapi-parser"; 

it("webapi test", async () => {
 // This still works
 webapi.WebApiParser.init();

  // These break as typscript says that webapi doesn't contain a member of model
  const api = new webapi.model.domain.WebApi();
  const model = new webapi.model.document.Document(api)
  ...
  expect(getBaseUri(model)).to.equal(
    "test-url-value"
  );
});

```

Looking at the d.ts file it does not seem as if model is exported from it at all either

**Comment by postatum** [comment]
Hi @monkey-jeff. I'm looking into it.

**Comment by postatum** [comment]
@monkey-jeff version 0.4.1 should fix this issue. Please let me know if it does.

**Comment by monkey-jeff** [comment]
Seems better but not completely fixed.  Her is some working code with require
```typescript
import { expect } from "chai";

// eslint-disable-next-line @typescript-eslint/no-var-requires
const webapi = require("webapi-parser");
const wap = webapi.WebApiParser;
const document = webapi.model.document;
const domain = webapi.model.domain;

import { getBaseUri } from "../src/template-helpers";

describe("Test getBaseUri template help function", () => {
  before(() => wap.init());

  it("returns correct base uri", async () => {
    const api = new domain.WebApi();
    api.withServer("test-url-value");
    const model = new document.Document(api);
    expect(getBaseUri(model)).to.equal("test-url-value");
  });
});
```
if I swap it out for an import it doesn't work and Ive tried `import webapi from "webapi-parser"` `import {default as webapi} from "webapi-parser"` and `import * as webapi from "webapi-parser" just to ensure.

It is now exposing the amf types but according to the docs here: https://raml-org.github.io/webapi-parser/constructing.html it should work like
```
async function main () {
  ...
  const api = new domain.WebApi()
  ...
  const model = new webapi.model.document.Document(api)
}
```

It seems like we are getting the models now, but directly from AMF and not the wrapped webapi-parser models that should be exported, so when I change it to ES6 syntax I get the following errors from my above code

```bash
test/template-helpers-get-base-uri.test.ts:30:23 - error TS2345: Argument of type 'Document' is not assignable to parameter of type 'WebApiBaseUnitWithEncodesModel'.
  Property 'getDeclarationByName' is missing in type 'Document' but required in type 'WebApiBaseUnitWithEncodesModel'.

30     expect(getBaseUri(new document.Document())).to.equal("");
                         ~~~~~~~~~~~~~~~~~~~~~~~

  ../../node_modules/webapi-parser/typings/webapi-parser.d.ts:12:3
    12   getDeclarationByName(name: string): amf.model.domain.AnyShape
         ~~~~~~~~~~~~~~~~~~~~
    'getDeclarationByName' is declared here.
test/template-helpers-get-base-uri.test.ts:36:41 - error TS2554: Expected 0 arguments, but got 1.

36     const model = new document.Document(api);
```

Looking at the code it is trying to create the pure AMF objects which don't have the above overloaded constructor or the 'getDeclarationByName' defined in the WebapiBaseUnit class.

Thanks for the quick reply!!!

-Jeff

**Comment by postatum** [comment]
Hi again @monkey-jeff.

> It is now exposing the amf types but according to the docs here: https://raml-org.github.io/webapi-parser/constructing.html it should work like

Thanks for pointing that out. It turns out our docs were a little outdated. I've just updated them.

Regarding import and your js snippet, here's the code I used for testing today and it worked for me. (I've tried to compile with `tsc`).

```js
import * as lib from "webapi-parser";
const wap = lib.WebApiParser;
const document = lib.model.document;
const domain = lib.model.domain;

const api = new domain.WebApi();
api.withServer("test-url-value");
const model = new lib.webapi.WebApiDocument().withEncodes(api);
model.getDeclarationByName('Foo');
```

**Comment by monkey-jeff** [comment]
Hi @postatum,

Thank you so much for solving this so quickly!

I have tested it and it seems to be working and also provides some more clarity around object definitions!
